gardenweb:
    image: doug/lights-webserver
    ports:
        - "8888:8080"
    links:
        - gardendb
gardendb:
    image: garden_oracle
    domainname: sorted.net
    hostname: lights-db
    ports:
        - "1521:1521"
