gardenweb:
    image: sortednet/lights-webserver
    ports:
        - "8888:8080"
    links:
        - lights-db.sorted.net


lights-db.sorted.net:
    image: sortednet/lights-db
    ports:
        - "1521:1521"
